#
# cron -> buildkite
#
# For every 1 minute, waymond will check if there is new jobs waiting to be scheduled in buildkite

[[trigger]]
type = "cron"
id = "global_cron"
expression = "*/1 * * * *"

[[trigger]]
type = "buildkite"
id = "my_buildkite_org"
# set BUILDKITE_TOKEN environment variable

[[connect]]
type = "direct"
id = "check_my_buildkite_org_queues_periodically"
from = "trigger.global_cron"
to = "trigger.my_buildkite_org"

[[scaler]]
type = "noop"
id = "noop"

[[connect]]
type = "direct"
id = "print_trigger_output"
from = "trigger.my_buildkite_org"
to = "scaler.noop"
[connect.transform]
method = "go_template"
data = """
{
  "asg_name": "{{ .queue }}",
  "desired_count": {{ .scheduled_jobs_count }}
}
"""